version: "3"
services:
    express:
        build:
            context: .
            dockerfile: Dockerfile
            environment:
                - DB_USER: ${DB_USER}
                - DB_PASS: ${DB_PASS}
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 1337:1337
        links:
            - mongodb
        command: "node src/server.js"

    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        # ports:
        #     - 27017:27017
        command: mongod  --bind_ip_all
